### ISSUE TITLE
Why does latex render incorrectly in the GitHub view of some tutorials?

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion-Cirq#173]
E.g., tutorial 3. It looks fine if I actually open the notebook but if I view it on GitHub the latex is a bit of a mess.

**Comment by babbush** [comment]
@Strilanc @kevinsung any ideas? This is really unfortunate.

**Comment by kevinsung** [comment]
Apparently stuff like `\begin{equation}` and `\begin{align}` does not work. You have to surround block equations by double dollar signs `$$`. Fixed in #231
