### ISSUE TITLE
Use sparse matrix instead of LinearOperator to compute expectation values.

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion-Cirq#244]
HamiltonianVariationalStudy converts its Hamiltonian into a LinearQubitOperator for the purposes of computing expectation values. I made this decision because using `get_sparse_operator` can consume a prohibitive amount of memory when there are enough qubits. However, we should be using `get_sparse_operator` when possible because computing expectation values with a sparse matrix is much faster than with a LinearQubitOperator. With a 12-qubit Hamiltonian I tested, this time went from around 25 seconds to 200 milliseconds.

I think the way to go is to default to using sparse matrix and have an option to use LinearOperator.

**Comment by babbush** [comment]
That sounds fine to me.
