### ISSUE TITLE
Change low rank Trotter step to use spatial low rank routine

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion-Cirq#254]
@jarrodmcc , @babbush any comments?

**Comment by kevinsung** [comment]
This should definitely work for LiH, right? How about a random Hamiltonian (generated using spatial orbitals, then lifted)?

**Comment by babbush** [comment]
By "work" I assume you mean "admit some rank truncation". You will not be able to truncate rank for an arbitrary random Hamiltonian. You should be able to truncate at least a couple eigenvectors for LiH though.

**Comment by kevinsung** [comment]
Well I'm also wondering if there is any additional structure being assumed on the Hamiltonian, other than spin symmetry.

**Comment by kevinsung** [comment]
It doesn't seem to work with a random spin-symmetric Hamiltonian.
