### ISSUE TITLE
broken demos

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion-Cirq#270]
Running the latest versions of OpenFermion, Cirq, and OpenFermion-Cirq, Tutorial III breaks when I try to run it. Apparently we aren't testing the demos properly so I suspect others are broken as well. In Tutorial III, the first cell runs fine but here's the output I get when I attempt to run the second cell:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-72a4786f2838> in <module>()
     18             time=time, omit_final_swaps=True,
     19             algorithm=custom_algorithm),
---> 20     strategy=cirq.InsertStrategy.EARLIEST)
     21 
     22 # Print circuit.

~/Desktop/Cirq/cirq/circuits/circuit.py in from_ops(strategy, device, *operations)
    112         """
    113         result = Circuit(device=device)
--> 114         result.append(operations, strategy)
    115         return result
    116 

~/Desktop/Cirq/cirq/circuits/circuit.py in append(self, moment_or_operation_tree, strategy)
    858             strategy: How to pick/create the moment to put operations into.
    859         """
--> 860         self.insert(len(self._moments), moment_or_operation_tree, strategy)
    861 
    862     def clear_operations_touching(self,

~/Desktop/Cirq/cirq/circuits/circuit.py in insert(self, index, moment_or_operation_tree, strategy)
    568         operations = list(ops.flatten_op_tree(ops.transform_op_tree(
    569             moment_or_operation_tree,
--> 570             self._device.decompose_operation)))
    571         for op in operations:
    572             self._device.validate_operation(op)

~/Desktop/Cirq/cirq/ops/op_tree.py in flatten_op_tree(root)
     63     if isinstance(root, collections.Iterable):
     64         for subtree in root:
---> 65             for item in flatten_op_tree(subtree):
     66                 yield item
     67         return

~/Desktop/Cirq/cirq/ops/op_tree.py in flatten_op_tree(root)
     62 
     63     if isinstance(root, collections.Iterable):
---> 64         for subtree in root:
     65             for item in flatten_op_tree(subtree):
     66                 yield item

~/Desktop/Cirq/cirq/ops/op_tree.py in <genexpr>(.0)
     95     if isinstance(root, collections.Iterable):
     96         return iter_transformation(
---> 97             transform_op_tree(subtree, op_transformation, iter_transformation)
     98             for subtree in root)
     99 

~/Desktop/OpenFermion-Cirq/openfermioncirq/trotter/simulate_trotter.py in simulate_trotter(qubits, hamiltonian, time, n_steps, order, algorithm, control_qubit, omit_final_swaps)
     97     trotter_step = _select_trotter_step(
     98             hamiltonian, order, algorithm,
---> 99             controlled = control_qubit is not None)
    100 
    101     # Get ready to perform Trotter steps

~/Desktop/OpenFermion-Cirq/openfermioncirq/trotter/simulate_trotter.py in _select_trotter_step(hamiltonian, order, algorithm, controlled)
    178     else:
    179         if order == 0:
--> 180             trotter_step = algorithm.asymmetric(hamiltonian)
    181             if trotter_step is None:
    182                 raise ValueError('The chosen Trotter step algorithm does not '

~/Desktop/OpenFermion-Cirq/openfermioncirq/trotter/algorithms/low_rank.py in asymmetric(self, hamiltonian)
     85                 self.truncation_threshold,
     86                 self.final_rank,
---> 87                 self.spin_basis)
     88 
     89     def controlled_asymmetric(self, hamiltonian: Hamiltonian

~/Desktop/OpenFermion-Cirq/openfermioncirq/trotter/algorithms/low_rank.py in __init__(self, hamiltonian, truncation_threshold, final_rank, spin_basis)
    116                 truncation_threshold=self.truncation_threshold,
    117                 final_rank=self.final_rank,
--> 118                 spin_basis=spin_basis))
    119 
    120         # Get scaled density-density terms and basis transformation matrices.

TypeError: low_rank_two_body_decomposition() got an unexpected keyword argument 'spin_basis'

**Comment by babbush** [comment]
Nevermind, there's no issue. This was my fault.

**Comment by Strilanc** [comment]
Why was it failing for you? Wrong virtualenv?

**Comment by babbush** [comment]
The version of OpenFermion I had installed included changes I had made in an unmerged feature branch. It was really just my fault.
