### ISSUE TITLE
Problem in developer installation of OpenFermion-Cirq

### ISSUE THREAD

**Issue by Zetinzeton** [quantumlib/OpenFermion-Cirq#299]
When trying to install OpenFermion-Cirq version 0.2.2.dev35 in developer mode, the installer requests the file runtime-requirements.txt, which is not present in the repository and makes the installation to fail. What is present is a file called requirements.txt. If I modify setup.py to change the name from runtime-requirements.txt to requirements.txt, then another error arises:
`error in openfermioncirq setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'+git://g'"`

**Comment by kevinsung** [comment]
#300 fixes the first issue (wrong reference to requirements file). As for the second issue, that's happening because we are near the end of a release cycle and need to direct our continuous integration services at the develop branches of Cirq and OpenFermion. A quick and dirty fix is just to remove or comment those lines from the requirements file, and manually install the development versions of Cirq and OpenFermion.

**Comment by Strilanc** [comment]
More generally, I don't think our developer install instructions should be telling devs to install openfermioncirq itself. Doing so creates ambiguity about whether `import openfermioncirq` is going to import the installed version or the source code you've been editing, which can result in some very confusing situations.

**Comment by kevinsung** [comment]
But the purpose of the `-e` option of `pip install` is to make it so that the source code you've been editing _is_ the installed version. I think it's more convenient to do `pip install -e .` than to have to manually set your PYTHONPATH (is that recommendation you're suggesting?).

**Comment by Strilanc** [comment]
Oh, really? I guess that does make sense then. I've always just edited my path, or used homebrew commands that include my working directory in the path before running python commands.

**Comment by kevinsung** [comment]
@Strilanc the solution to this is to put the dev releases in `requirements.txt`, right?

**Comment by Strilanc** [comment]
Correct. Once we depend on `cirq~=0.4.0.dev` and similarly for openfermion, this should stop being a problem.

**Comment by kevinsung** [comment]
master now depends on the dev versions of Cirq and OpenFermion.
