### ISSUE TITLE
Replace cirq.Symbol with sympy.Symbol

### ISSUE THREAD

**Issue by vtomole** [quantumlib/OpenFermion-Cirq#332]
`cirq.Symbol `just got removed some minutes ago. We have to get OpenFermionCirq up to date.

Kind of related: @Strilanc Where have the discussions about merging OpenFermion-Cirq into Cirq gone? I've merged it on a local branch and things have been smooth thus far.

**Comment by Strilanc** [comment]
I'm still a bit wary of making cirq depend on openfermion, when it's possible we might want to go in the reverse direction. It would also make openfermion-cirq differn from the other openfermion-X libraries.

That being said, it does feel a bit silly that they're separate. And we do move things between the two more often than we would if they were properly distinct.
