### ISSUE TITLE
Scipy comb deprecated

### ISSUE THREAD

**Issue by jacobmarks** [quantumlib/OpenFermion-Cirq#356]
when importing openfermioncirq in colab,
`from scipy.misc import comb, factorial` causes problem "cannot import name comb"

**Comment by vtomole** [comment]
Closing https://github.com/quantumlib/OpenFermion/issues/536 will close this too.

**Comment by kevinsung** [comment]
The reason for this is that the pip version of openfermioncirq is pinned to OpenFermion 0.9.0. We need to cut a new release of openfermioncirq to fix this.
