### ISSUE TITLE
Incremental coverage doesn't user .coveragerc

### ISSUE THREAD

**Issue by ncrubin** [quantumlib/OpenFermion-Cirq#384]
It seems to complain about _test.py files and files where no coverage pragmas have been added.  Does this functionality check the.coveragerc file?

**Comment by Strilanc** [comment]
The issue is actually that the coverage tool which creates annotations does pay attention to this configuration, but then the coverage checker notices that the tests have no coverage annotation-- indicating they are not covered.

We do want to include test code in the coverage check.
