### ISSUE TITLE
check/mypy throws an error on fresh install 

### ISSUE THREAD

**Issue by ncrubin** [quantumlib/OpenFermion-Cirq#386]
Start with a fresh conda env.

Installing `pip install -r dev_tools/conf/pip...`

and then running `check/mypy` throws the following error:

site-packages/cirq/google/api/v2/device_pb2.pyi:97: error: invalid type comment or annotation

Travis doesn't seem to encounter this so maybe there is a version issue somewhere.

**Comment by kevinsung** [comment]
Does this happen when you run `check/mypy` in Cirq?

**Comment by kevinsung** [comment]
It's strange to me that running `check/mypy` in the openfermioncirq repo should raise a warning from a file in Cirq.
