### ISSUE TITLE
type checking and coverage should be removed from build=pass

### ISSUE THREAD

**Issue by ncrubin** [quantumlib/OpenFermion-Cirq#387]
These are extra features for the developer and do not effect the logic or testing of a feature.  They should not hinder additions to the library.  They should be removed from the build == pass requirement.

**Comment by vtomole** [comment]
>  and do not effect the logic or testing

coverage does affect testing in the sense that uncovered code is untested code.  I vote against this because the checks are easiest way of enforcing code quality. Anyway, this is something that's important to bring up in the sync.

**Comment by ncrubin** [comment]
With no way of editing the coverage or testing rules this will fail 100% of the time whenever a new test is added.  This coverage feature is incomplete.

**Comment by ncrubin** [comment]
As @Strilanc explained...code checks test and tests check code.  Coverage checks this relationship.  Now that I know how to ignore the coverage when tests are ignored (a small price considering the action) this is no longer an issue. As an example, consider a long running system test.  That should not be run as a merge test.  But if the test is ignored the coverage check sees that the code in the test is never run.  This is remedied by adding `# coverage: ignore` to whenever tests are skipped for some reason.  Skipping tests is okay...they just come with the price of two pragmas.
